AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  SWToken:
    Type: String
    Description: SW_APM_API_TOKEN value
  SWDataCenter:
    Type: String
    Default: na-01
    Description: SW_APM_DATA_CENTER value
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: false
      OpenApiVersion: 3.0.2
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Architectures:
        - arm64
      CodeUri: function/.
      Description: Call the AWS Lambda API
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/solarwinds-apm/wrapper
          OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector-dev.yaml
          #OPENTELEMETRY_EXTENSION_LOG_LEVEL: info
          OTEL_SERVICE_NAME: lin-test-python-lambda-service
          SW_APM_API_TOKEN: !Ref SWToken
          SW_APM_DATA_CENTER: !Ref SWDataCenter
          #SW_APM_DEBUG_LEVEL: 6
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      #Tracing: Active
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: GET
      Layers:
        - !Ref libs
        - arn:aws:lambda:us-east-1:851060098468:layer:opentelemetry-collector-arm64-0_0_8:2
        - arn:aws:lambda:us-east-1:851060098468:layer:solarwinds-apm-python-arm64-1_6_0_2:1
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-python-lib
      Description: Dependencies for the blank-python sample app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8
