AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  SWToken:
    Type: String
    Description: SW_APM_API_TOKEN value
  SWDataCenter:
    Type: String
    Default: na-01
    Description: SW_APM_DATA_CENTER value
Resources:
  function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/blank-java.zip
      Handler: example.Handler::handleRequest
      Runtime: java11
      Description: Java function
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/swi-handler
          OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /opt/collector-dev.yaml
          #OTEL_JAVAAGENT_DEBUG: "true"
          OTEL_SERVICE_NAME: lin-test-java-lambda-service
          SW_APM_API_TOKEN: !Ref SWToken
          SW_APM_DATA_CENTER: !Ref SWDataCenter
          SW_APM_TRANSACTION_NAME: envVarSetTransaction
          #SW_APM_DEBUG_LEVEL: trace
      MemorySize: 2048
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      #Tracing: Active
      Layers:
        - !Ref libs
        - arn:aws:lambda:us-east-1:858939916050:layer:opentelemetry-collector-amd64-staging-0_0_3:2
        - arn:aws:lambda:us-east-1:858939916050:layer:solarwinds-apm-java-2_0_0:2
  function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/blank-java.zip
      Handler: example.Handler::handleRequest
      Runtime: java11
      Description: Java function
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/swi-handler
          OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /opt/collector-dev.yaml
          #OTEL_JAVAAGENT_DEBUG: "true"
          OTEL_SERVICE_NAME: lin-test-java-lambda-service
          SW_APM_API_TOKEN: !Ref SWToken
          SW_APM_DATA_CENTER: !Ref SWDataCenter
          #SW_APM_DEBUG_LEVEL: trace
      MemorySize: 2048
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      #Tracing: Active
      Layers:
        - !Ref libs
        - arn:aws:lambda:us-east-1:858939916050:layer:opentelemetry-collector-amd64-staging-0_0_3:2
        - arn:aws:lambda:us-east-1:858939916050:layer:solarwinds-apm-java-2_0_0:2
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-java-lib
      Description: Dependencies for the blank-java sample app.
      ContentUri: build/blank-java-lib.zip
      CompatibleRuntimes:
        - java11